In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("mpg.csv")

df.dtypes

df.horsepower.unique()  #cleaning of the data, found "?" unwanted character in horsepower

df=df[df.horsepower !="?"]  #remove unwanted characters

df.horsepower.unique()   #cleaned

df.horsepower= df.horsepower.astype(float)

df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
name             object
dtype: object

In [4]:
from sklearn.metrics import mean_squared_error,r
from sklearn.model_selection import train_test_split
df=df
training_features = [ 'acceleration','origin','displacement','model_year','horsepower']
target = 'mpg'

#test train split
X_train, X_test, Y_train, Y_test = train_test_split(df[training_features],
                                                    df[target],
                                                     test_size=0.145, random_state=301)
#model creation
from sklearn import linear_model

model = linear_model.Ridge(alpha=10.0)    # 0 to infinity 

# if alpha is zero, we'll get linear model
#increasing alpha decreases r square since mse increases and the focus shifts on the coefficients
#because we are minimizing MSE+alpha(sum of squared coefficients)

#model fit
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)


Mean squared error: 6.53
R Square score: 0.89
Coefficients: 
 [-0.37730066  1.52209833 -0.02231451  0.65798284 -0.08353246]
Intercept:
 -10.04004182088682


In [5]:
# when alpha=100
model = linear_model.Ridge(alpha=100.0)    # 0 to infinity 

# if alpha is zero, we'll get linear model
#increasing alpha decreases r square since mse increases and the focus shifts on the coefficients
#because we are minimizing MSE+alpha(sum of squared coefficients)

#model fit
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)


Mean squared error: 6.68
R Square score: 0.89
Coefficients: 
 [-0.35639938  0.92102996 -0.02751914  0.64282097 -0.07636543]
Intercept:
 -8.00991811677686


In [8]:
#when alpha is 10000
model = linear_model.Ridge(alpha=10000.0)    # 0 to infinity 

# if alpha is zero, we'll get linear model
#increasing alpha decreases r square since mse increases and the focus shifts on the coefficients
#because we are minimizing MSE+alpha(sum of squared coefficients)

#model fit
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)


Mean squared error: 10.34
R Square score: 0.83
Coefficients: 
 [-0.04024502  0.02068064 -0.03899286  0.1850024  -0.05844629]
Intercept:
 23.622558988855122


In [9]:
#when alpha is 1000000
model = linear_model.Ridge(alpha=1000000)    # 0 to infinity 

# if alpha is zero, we'll get linear model
#increasing alpha decreases r square since mse increases and the focus shifts on the coefficients
#because we are minimizing MSE+alpha(sum of squared coefficients)

#model fit
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)


Mean squared error: 13.18
R Square score: 0.78
Coefficients: 
 [ 0.0004701   0.00036772 -0.04191619  0.00326192 -0.01870197]
Intercept:
 33.2885811230444


In [10]:
#when alpha is 100000000
model = linear_model.Ridge(alpha=100000000)    # 0 to infinity 

# if alpha is zero, we'll get linear model
#increasing alpha decreases r square since mse increases and the focus shifts on the coefficients
#because we are minimizing MSE+alpha(sum of squared coefficients)

#model fit
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
print("Mean squared error: %.2f"
              % mean_squared_error(Y_test, predicted))
print('R Square score: %.2f' % r2_score(Y_test, predicted))

print('Coefficients: \n', model.coef_)
print('Intercept:\n',model.intercept_)


Mean squared error: 58.71
R Square score: 0.03
Coefficients: 
 [ 2.89250809e-05  1.12423408e-05 -2.00165343e-03  5.36204909e-05
 -7.28557226e-04]
Intercept:
 24.105931836276387
